### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [ninanazarova/regexp#2]
Хорошая работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже. В проекте ветка develop отстает от ветки master, так не должно быть. Ветка develop должна содержать все актуальные изменения и после должна мержится с master.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Надо исправить**
- **develop должна быть актуальной веткой, develop должна не отставать от master. Сначала делаете пуш в develop только потом мержите с мастер.** Подробнее [git push в master плохо](https://ru.stackoverflow.com/questions/672926/%D0%A1%D0%BB%D0%B0%D1%82%D1%8C-git-push-%D0%B2-master-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE). Еще можно почитать эту статью, 4 пункт [(Упс… Я коммитнул изменения в master)](https://habr.com/ru/company/flant/blog/419733/)
- `example@yandex` - не хватает верхнего уровня домена, например, .ru
- `ya@x.ru` - доменное имя может состоять из одного символа
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- `http://11.11.11.11:0000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Можно лучше**
- С комитами все отлично, но можно немного лучше. Часто возникает соблазн написать комментарий к коммиту вида "fixes" или "first commit". Лучше описывать коммиты подробнее.
Делать коммиты, когда:
1) выполнил единицу работы
2) сделал изменения, которые потом может потребоваться отменить
Интересная статья по [ссылке](https://habr.com/ru/company/Voximplant/blog/276695/)

**Comment by ninanazarova** [comment]
Добрый вечер!

Внесла правки) [вот код](https://github.com/ninanazarova/regexp)
Спасибо!

**Comment by talantbekov123** [comment]
С адресами что-то пошло не так, прошу проверить.

**Надо исправить**
- `http://ya.ru` - Не проходит валидацию корректный домен
- `https://www.ya.ru` - Не проходит валидацию корректный домен
- `http://2-domains.ru` - Не проходит валидацию корректный домен
- `http://ya.com:30` - Не проходит валидацию корректный домен
- `http://ya-ya-ya.ru` - Не проходит валидацию корректный домен
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- `http://11.11.11.11:0000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Comment by talantbekov123** [comment]
Хорошая работа, все комментарии исправлены! Похвально! Принимаю.
